name: vplayer
version: ${project.version}
main: net.kunmc.lab.vplayer.VideoPlayer
api-version: 1.16
authors: [Kamesuta]

permissions:
  vdisplay.*:
    children:
      vdisplay.display: true
      vdisplay.player: true
  vdisplay.display:
    default: op
  vdisplay.player:
    default: op